version: '3.8'

services:
  zend:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
    networks:
      - pgsql_network

  postgres:
    image: postgres:9.6
    container_name: postgres_zf2
    restart: always
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - pgsql_network

networks:
  pgsql_network:
    driver: bridge
